name: Python script on build failure
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  trigger-on-failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Python script
        run: python HelloWorld.py
